// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jptkayenlumumcsdzzqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwdGtheWVubHVtdW1jc2R6enF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDc2NTAsImV4cCI6MjA2NTUyMzY1MH0.gK52lhEBOSJeul27pkSRYJgZdvnar73z1jc5zjFYDl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);